rtx.terrainBaker.cascadeMap.defaultHeight = 20
rtx.playerModel.enableVirtualInstances = True
rtx.enableAlphaBlend = True
rtx.worldSpaceUiTextures = 0x9842B25662E1DBDF, -0x525C851269A961B7
rtx.texturemanager.fixedBudgetEnable = False
rtx.terrainBaker.cascadeMap.levelResolution = 4096
rtx.terrainTextures = 0x85921E7690AE8F4E, 0xA6B69F6C017AC9DA, 0xE2ED852917B9DFF7
rtx.raytracedRenderTarget.enable = True
rtx.ignoreAllVertexColorBakedLighting = True
rtx.terrainBaker.enableBaking = True
rtx.terrainBaker.cascadeMap.useTerrainBBOX = False
rtx.terrainBaker.clearTerrainBeforeBaking = True
rtx.enableRaytracing = True
rtx.terrainBaker.disableBackFaceCulling = False
rtx.terrainBaker.debugDisableBinding = False
rtx.terrainBaker.cascadeMap.expandLastCascade = True
rtx.ignoreTextures = -0x9842B25662E1DBDF, -0xBD0BE6DE46AC71C4, -0xFADA49AB6A83BDFA
rtx.playerModel.enablePrimaryShadows = True
rtx.terrainBaker.cascadeMap.levelHalfWidth = 0.32
rtx.enableCulling = True
rtx.debugView.composite.compositeViewIdx = 0
rtx.terrain.terrainAsDecalsEnabledIfNoBaker = False
rtx.enableCullingInSecondaryRays = False
rtx.captureInstanceStageName = capture_{timestamp}.usda
rtx.uiTextures = 0x005178BCA85A9358, 0x0FD7434A6F0C8F2C, 0x4A8371237900CD45, 0x87CE178AB95EA9B3, 0xA06E0898509EA5C4, 0xB21F6542113EC756, 0xBAE0D4569D1D43A2, 0xC8A07FB7623EA9AA, 0xCAFECC430B32D44B, 0xE02D03617A2395AB, 0xE920171AFCCA2726, -0x525C851269A961B7
rtx.graph.enable = False
rtx.terrainBaker.cascadeMap.defaultHalfWidth = 80
rtx.debugView.debugViewIdx = 0
rtx.useVertexCapturedNormals = True
rtx.enableAlphaTest = True
rtx.hideInstanceTextures = 0x85921E7690AE8F4E, 0xE2ED852917B9DFF7, -0x248267415AF14748, -0x9D7CAA0A1E511B70, -0xBA2A226DA4FB0C67
rtx.playerModel.enableInPrimarySpace = False
rtx.enableEmissiveBlendModeTranslation = True
rtx.terrainBaker.cascadeMap.maxLevels = 9
